package ste.mjga;

/**
 * Generated by MClassProcessor - DO NOT EDIT
 */
public class MJGA {
    private MJGA() {}

    public static Person Person() {
        return new Person();
    }

    public static Person Person(java.lang.String name, int age) {
        return new Person(name, age);
    }

}
