/**
 * Copyright 2026 the original author or authors from the lazy-java project
 * (https://github.com/stefanofornari/lazy-java).
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package ste.mjga.processor;

import com.google.auto.service.AutoService;
import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.Element;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.Modifier;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.util.*;
import java.io.Writer;
import java.io.IOException;

/**
 * Annotation processor for @MClass that generates static factory methods
 * in helper classes to enable simpler constructor syntax.
 */
@SupportedAnnotationTypes("ste.mjga.MClass")
@SupportedSourceVersion(SourceVersion.RELEASE_11)
@AutoService(Processor.class)
public class MClassProcessor extends AbstractProcessor {

    public MClassProcessor() {
        System.out.println("CREATED!!!");
    }

    // Map to collect all annotated classes by package
    private final Map<String, List<TypeElement>> classesByPackage = new HashMap<>();

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            return false;
        }

        boolean foundNew = false;
        for (TypeElement annotation : annotations) {
            Set<? extends Element> annotatedElements = roundEnv.getElementsAnnotatedWith(annotation);

            for (Element element : annotatedElements) {
                if (element instanceof TypeElement) {
                    TypeElement classElement = (TypeElement) element;
                    String packageName = getPackageName(classElement);
                    List<TypeElement> classes = classesByPackage.computeIfAbsent(packageName, k -> new ArrayList<>());
                    if (!classes.contains(classElement)) {
                        classes.add(classElement);
                        foundNew = true;
                    }
                }
            }
        }

        if (foundNew) {
            generateMJGAClasses();
        }

        return true;
    }

    private String getPackageName(TypeElement classElement) {
        Element packageElement = classElement.getEnclosingElement();
        while (packageElement != null && !(packageElement instanceof PackageElement)) {
            packageElement = packageElement.getEnclosingElement();
        }
        return packageElement != null ? ((PackageElement) packageElement).getQualifiedName().toString() : "";
    }

    private void generateMJGAClasses() {
        for (Map.Entry<String, List<TypeElement>> entry : classesByPackage.entrySet()) {
            generateMJGAClass(entry.getKey(), entry.getValue());
        }
    }

    private void generateMJGAClass(String packageName, List<TypeElement> classes) {
        String simpleName = "MJGA";
        String fullClassName = packageName.isEmpty() ? simpleName : packageName + "." + simpleName;

        try {
            JavaFileObject sourceFile = processingEnv.getFiler().createSourceFile(fullClassName);

            try (Writer writer = sourceFile.openWriter()) {
                if (!packageName.isEmpty()) {
                    writer.write("package " + packageName + ";\n\n");
                }
                writer.write("/**\n");
                writer.write(" * Generated by MClassProcessor - DO NOT EDIT\n");
                writer.write(" */\n");
                writer.write("public class " + simpleName + " {\n");
                writer.write("    private " + simpleName + "() {}\n\n");

                for (TypeElement classElement : classes) {
                    generateFactoryMethods(writer, classElement);
                }

                writer.write("}\n");
            }
        } catch (IOException e) {
            // This is expected if MJGA was already created in a previous round (e.g. main vs test)
            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                "Helper class already exists for " + fullClassName);
        }
    }

    private void generateFactoryMethods(Writer writer, TypeElement classElement) throws IOException {
        String qualifiedName = classElement.getQualifiedName().toString();
        String packageName = getPackageName(classElement);
        String relativeName = (packageName.isEmpty() || !qualifiedName.startsWith(packageName + "."))
            ? qualifiedName
            : qualifiedName.substring(packageName.length() + 1);

        String methodName = classElement.getSimpleName().toString();

        for (Element element : classElement.getEnclosedElements()) {
            if (element instanceof ExecutableElement) {
                ExecutableElement method = (ExecutableElement) element;
                if (method.getSimpleName().toString().equals("<init>") && method.getModifiers().contains(Modifier.PUBLIC)) {
                    generateFactoryMethod(writer, methodName, relativeName, method);
                }
            }
        }
    }

    private void generateFactoryMethod(Writer writer, String methodName, String className, ExecutableElement constructor) throws IOException {
        List<? extends javax.lang.model.element.VariableElement> parameters = constructor.getParameters();

        writer.write("    public static " + className + " " + methodName + "(");
        for (int i = 0; i < parameters.size(); i++) {
            if (i > 0) writer.write(", ");
            javax.lang.model.element.VariableElement param = parameters.get(i);
            writer.write(param.asType().toString() + " " + param.getSimpleName());
        }
        writer.write(") {\n");
        writer.write("        return new " + className + "(");
        for (int i = 0; i < parameters.size(); i++) {
            if (i > 0) writer.write(", ");
            writer.write(parameters.get(i).getSimpleName().toString());
        }
        writer.write(");\n");
        writer.write("    }\n\n");
    }
}