/**
 * Copyright 2026 the original author or authors from the lazy-java project
 * (https://github.com/stefanofornari/lazy-java).
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package ste.lazyjava.processor;

import com.google.auto.service.AutoService;
import ste.lazyjava.annotation.£;
import ste.lazyjava.annotation.LClass;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.Writer;
import java.io.IOException;
import java.util.*;
import java.util.logging.Logger;

/**
 * Annotation processor for {@link £} that generates package-level {@code £}
 * interfaces with static factory methods.
 *
 * <p>Usage:
 * <pre>
 * {@code @£}
 * public class Person {
 *     public Person() {}
 *     public Person(String name, int age) {}
 * }
 *
 * // Generated in the same package:
 * // public interface £ {
 * //     public static Person Person() { return new Person(); }
 * //     public static Person Person(String name, int age) { return new Person(name, age); }
 * // }
 * </pre>
 */
@SupportedAnnotationTypes({
    "ste.lazyjava.annotation.£",
    "ste.lazyjava.annotation.LClass"
})
@SupportedSourceVersion(SourceVersion.RELEASE_21)
@AutoService(Processor.class)
public class £Processor extends AbstractProcessor {

    private final Logger LOG = Logger.getLogger(getClass().getName());
    private final Map<String, List<TypeElement>> classesByPackage = new LinkedHashMap<>();

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            return false;
        }

        boolean foundNew = false;
        for (TypeElement annotation : annotations) {
            LOG.finest("processing annotation " + annotation);
            Set<? extends Element> annotatedElements = roundEnv.getElementsAnnotatedWith(annotation);
            for (Element element : annotatedElements) {
                if (element instanceof TypeElement classElement) {
                    String packageName = getPackageName(classElement);
                    LOG.finest("element " + classElement + " in package " + packageName);
                    classesByPackage.computeIfAbsent(packageName, k -> new ArrayList<>()).add(classElement);
                    foundNew = true;
                }
            }
        }

        if (foundNew) {
            generateHelperClasses();
        }

        return true;
    }

    private String getPackageName(TypeElement classElement) {
        Element packageElement = classElement.getEnclosingElement();
        while (packageElement != null && !(packageElement instanceof PackageElement)) {
            packageElement = packageElement.getEnclosingElement();
        }
        return packageElement != null ? ((PackageElement) packageElement).getQualifiedName().toString() : "";
    }

    private void generateHelperClasses() {
        for (Map.Entry<String, List<TypeElement>> entry : classesByPackage.entrySet()) {
            generatePackageInterface(entry.getKey(), entry.getValue());
        }
    }

    private void generatePackageInterface(String packageName, List<TypeElement> classes) {
        final String simpleName = "£";
        final String fullClassName = packageName.isEmpty() ? simpleName : packageName + "." + simpleName;

        LOG.info("generating interface " + fullClassName);

        try {
            JavaFileObject sourceFile = processingEnv.getFiler().createSourceFile(fullClassName);

            try (Writer writer = sourceFile.openWriter()) {
                if (!packageName.isEmpty()) {
                    writer.write("package " + packageName + ";\n\n");
                }
                writer.write("/**\n");
                writer.write(" * Generated by £Processor - DO NOT EDIT\n");
                writer.write(" */\n");
                writer.write("public interface " + simpleName + " {\n\n");

                for (TypeElement classElement : classes) {
                    generateFactoryMethods(writer, classElement);
                }

                writer.write("}\n");
            }
        } catch (IOException e) {
            LOG.severe("helper interface already exists for " + fullClassName);
            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                "Helper interface already exists for " + fullClassName);
        }
    }

    private void generateFactoryMethods(Writer writer, TypeElement classElement) throws IOException {
        final String qualifiedName = classElement.getQualifiedName().toString();
        final String packageName = getPackageName(classElement);
        final String relativeName = (packageName.isEmpty() || !qualifiedName.startsWith(packageName + "."))
            ? qualifiedName
            : qualifiedName.substring(packageName.length() + 1);

        final String methodName = classElement.getSimpleName().toString();

        for (Element element : classElement.getEnclosedElements()) {
            if (element instanceof ExecutableElement method) {
                if (method.getSimpleName().toString().equals("<init>") && method.getModifiers().contains(Modifier.PUBLIC)) {
                    generateFactoryMethod(writer, methodName, relativeName, method);
                }
            }
        }
    }

    private void generateFactoryMethod(Writer writer, String methodName, String className, ExecutableElement constructor) throws IOException {
        final List<? extends VariableElement> parameters = constructor.getParameters();

        LOG.info("generating factory " + methodName);

        writer.write("    public static " + className + " " + methodName + "(");
        for (int i = 0; i < parameters.size(); i++) {
            if (i > 0) writer.write(", ");
            VariableElement param = parameters.get(i);
            writer.write(param.asType().toString() + " " + param.getSimpleName());
        }
        writer.write(") {\n");
        writer.write("        return new " + className + "(");
        for (int i = 0; i < parameters.size(); i++) {
            if (i > 0) writer.write(", ");
            writer.write(parameters.get(i).getSimpleName().toString());
        }
        writer.write(");\n");
        writer.write("    }\n\n");
    }
}
